<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Event;
use Carbon\Carbon;

class CreateEventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // Event::insert([
      //   [
      //     'title' => 'Event Title1',
      //     'venue_name' => 'Vincent NightClub',
      //     'event_planner_id' => 2,
      //     'organizer_id' => 1,
      //     'type_id' => 1,    
      //     'category_id' => 1,
      //     'sub_category_id' => 2,
      //     'country_id' => 1,
      //     'state_id' => 3,
      //     'city' => 'New York',
      //     'zipcode' => '23453',
      //     'location_type' => 'venue', 
      //     'address' => 'dummy address1',
      //     'url' => null,
      //     'event_start' => Carbon::now()->addDays(15),
      //     'start_time' => '10:00',
      //     'event_end' => Carbon::now()->addDays(20),
      //     'end_time' => '11:30',
      //     'display_start_time' => '1',
      //     'display_end_time' => '1',
      //     'image' => 'http://localhost/frimix-app/public/storage/eventImages/2/event1.jpg',
      //     'summary' => 'dummy summary',
      //     'details' => 'dummy details',
      //     'ticket_type' => 'paid',
      //     'name' => 'tick1',
      //     'available_quantity' => '298',
      //     'total_quantity' => '300',
      //     'price' => '20',
      //     'sale_start' => Carbon::now()->subDays(7),
      //     'sale_start_time' => '15:00',
      //     'sale_end' => Carbon::now()->addDays(7),
      //     'sale_end_time' => '11:30',
      //     'max_ticket' => '10',
      //     'min_ticket' => '1',
      //     'ticket_description' => 'dummy ticket description',
      //     'status' => 1,
      //     'created_at' => Carbon::now(),
      //     'updated_at' => Carbon::now()
      //   ],
      //   [
      //     'title' => 'Event Title2',
      //     'venue_name' => 'Slate & Crystal Events',
      //     'event_planner_id' => 2,
      //     'organizer_id' => 1,
      //     'type_id' => 3,    
      //     'category_id' => 7,
      //     'sub_category_id' => 8,
      //     'country_id' => 1,
      //     'state_id' => 3,
      //     'city' => 'Chicago',
      //     'zipcode' => '452634',
      //     'location_type' => 'online-event', 
      //     'address' => 'dummy address2',
      //     'url' => 'https://us04web.zoom.us/j/72807749086?pwd=ZuuiRCMq6kXTZYAF3TAt_Lzz2Cz15s.1',
      //     'event_start' => Carbon::now()->addDays(10),
      //     'start_time' => '14:00',
      //     'event_end' => Carbon::now()->addDays(16),
      //     'end_time' => '14:30',
      //     'display_start_time' => '1',
      //     'display_end_time' => '1',
      //     'image' => 'http://localhost/frimix-app/public/storage/eventImages/2/event1.jpg',
      //     'summary' => 'dummy summary',
      //     'details' => 'dummy details',
      //     'ticket_type' => 'free',
      //     'name' => 'tick1',
      //     'available_quantity' => '298',
      //     'total_quantity' => '300',
      //     'price' => null,
      //     'sale_start' => Carbon::now()->subDays(10),
      //     'sale_start_time' => '15:00',
      //     'sale_end' => Carbon::now()->addDays(7),
      //     'sale_end_time' => '11:30',
      //     'max_ticket' => '10',
      //     'min_ticket' => '1',
      //     'ticket_description' => 'dummy ticket description',
      //     'status' => 1,
      //     'created_at' => Carbon::now(),
      //     'updated_at' => Carbon::now()
      //   ],
      //   [
      //     'title' => 'Event Title3',
      //     'venue_name' => 'Vincent Club',
      //     'event_planner_id' => 3,
      //     'organizer_id' => 3,
      //     'type_id' => 6,    
      //     'category_id' => 1,
      //     'sub_category_id' => 2,
      //     'country_id' => 1,
      //     'state_id' => 7,
      //     'city' => 'New Jersy',
      //     'zipcode' => '23453',
      //     'location_type' => 'venue', 
      //     'address' => 'dummy address3',
      //     'url' => null,
      //     'event_start' => Carbon::now()->addDays(15),
      //     'start_time' => '10:00',
      //     'event_end' => Carbon::now()->addDays(20),
      //     'end_time' => '11:30',
      //     'display_start_time' => '1',
      //     'display_end_time' => '1',
      //     'image' => 'http://localhost/frimix-app/public/storage/eventImages/4/event3.jpg',
      //     'summary' => 'dummy summary',
      //     'details' => 'dummy details',
      //     'ticket_type' => 'paid',
      //     'name' => 'tick1',
      //     'available_quantity' => '146',
      //     'total_quantity' => '150',
      //     'price' => '10',
      //     'sale_start' => Carbon::now()->subDays(9),
      //     'sale_start_time' => '15:00',
      //     'sale_end' => Carbon::now()->addDays(7),
      //     'sale_end_time' => '11:30',
      //     'max_ticket' => '3',
      //     'min_ticket' => '1',
      //     'ticket_description' => 'dummy ticket description',
      //     'status' => 1,
      //     'created_at' => Carbon::now(),
      //     'updated_at' => Carbon::now()
      //   ],
      // ]);
    }
}